# Generated by Django 4.2.16 on 2024-10-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20241030_1952'),
    ]

    operations = [
    ]
